# =============================================================================
# Read the Docs (RTD) - Configuration v2
# Official docs: https://docs.readthedocs.io/en/stable/config-file/v2.html
# Place this file at the ROOT of your repository as `.readthedocs.yml`
# =============================================================================

# Required: configuration schema version
version: 2

# -----------------------------------------------------------------------------
# Sphinx (documentation generator)
# -----------------------------------------------------------------------------
sphinx:
  # Path to the Sphinx configuration file (conf.py)
  configuration: docs/conf.py

  # Optional: Treat warnings as errors (fails the build if there are warnings)
  # Recommended when docs are stable, to keep quality high.
  fail_on_warning: false

# -----------------------------------------------------------------------------
# Extra output formats in addition to the default HTML
# -----------------------------------------------------------------------------
formats:
  - pdf          # Generates a PDF (via LaTeX) of your documentation
  # - epub       # Uncomment to generate an EPUB file

# -----------------------------------------------------------------------------
# Build environment configuration
# -----------------------------------------------------------------------------
build:
  os: ubuntu-22.04       # OS used for building
  tools:
    python: "3.11"       # Python version for the build

# -----------------------------------------------------------------------------
# How to install dependencies for building the docs
# -----------------------------------------------------------------------------
python:
  install:
    # 1) Install the package itself first (also installs runtime dependencies)
    #    This allows autodoc and imports from the package in the docs.
    - { path: ., method: pip }

    # 2) Documentation-specific dependencies
    #    This should contain what Sphinx and its extensions require
    - requirements: docs/requirements.txt

    # TIP:
    # - If your docs import heavy dependencies (e.g., numpy, pandas) and
    #   builds are slow, you can mock them in `docs/conf.py`:
    #       autodoc_mock_imports = ["numpy", "pandas"]
    # - If you need extras for docs (e.g., biorempp[docs]), replace with:
    #   - { path: ".[docs]", method: pip }
