name: biorempp
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python>=3.8   # Recomendo >=3.8 (3.6 está deprecated e a maioria das libs não suporta mais)
  - pip
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  - matplotlib
  - ipympl
  - seaborn
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - pip:
      - -e .



  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
