version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: "%(asctime)s | %(levelname)-8s | %(name)-25s | %(funcName)-15s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  simple:
    format: "%(levelname)s - %(name)s - %(message)s"
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "function": "%(funcName)s", "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/biorempp.log
    encoding: utf-8
    mode: a
  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/biorempp_errors.log
    encoding: utf-8
    mode: a

loggers:
  biorempp:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  biorempp.input_processing:
    level: INFO
    handlers: [console, file]
    propagate: false
  biorempp.utils:
    level: DEBUG
    handlers: [file]
    propagate: false

root:
  level: WARNING
  handlers: [console]
